# Generated by Django 4.0.2 on 2022-03-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='date',
        ),
        migrations.AddField(
            model_name='display',
            name='from_date',
            field=models.DateField(default='2022-01-01', verbose_name='from date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='display',
            name='to_date',
            field=models.DateField(default='2022-01-02', verbose_name='to date'),
            preserve_default=False,
        ),
    ]
